CREATE TABLE OT.PERSON (
	ID_PERSON NUMBER(19) NOT NULL,
	NM_PERSON VARCHAR2(150 BYTE) NOT NULL,
	NM_MIDDLE VARCHAR2(100 BYTE) NOT NULL,
	NM_FAMILY VARCHAR2(100 BYTE) NOT NULL,
	ID_ISSN VARCHAR2(50 BYTE) NULL,
	DT_CREATED DATE NOT NULL,
	ST_PERSON VARCHAR2(1 BYTE) NULL,
	CONSTRAINT PK_PERSON PRIMARY KEY(ID_PERSON)
		NOT DEFERRABLE VALIDATE
);

ALTER TABLE OT.PERSON
	ADD ( CONSTRAINT UK_PERSON_ISSN
UNIQUE (ID_ISSN)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE OT.PERSON
	ADD ( CONSTRAINT CK_PERSON_STATE CHECK (ST_PERSON in ('0','1'))
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

CREATE SEQUENCE OT.SEQ_PERSON
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;

