CREATE TABLE OT.USERS (
    ID_PERSON NUMBER(10) NOT NULL,
    DS_USERNAME VARCHAR2(255 BYTE) NOT NULL,
    DS_PASSWORD VARCHAR2(100 BYTE) NOT NULL,
    DS_EMAIL VARCHAR2(255 BYTE) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY(ID_PERSON) NOT DEFERRABLE VALIDATE
);

ALTER TABLE OT.USERS
	ADD ( CONSTRAINT UK_USERNAME
UNIQUE (DS_USERNAME)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE  )
;

ALTER TABLE OT.USERS
	ADD ( CONSTRAINT FK_PERSON_USER
FOREIGN KEY(ID_PERSON)
REFERENCES OT.PERSON(ID_PERSON)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;

